export const MOCK_TURFS = [
    {
        id: '1',
        name: 'Green Field Arena',
        location: 'Indiranagar, Bangalore',
        distance: '1.2 km',
        rating: 4.8,
        reviewCount: 124,
        price: 800,
        priceUnit: 'hour',
        sport: 'Football',
        image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
            'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',
            'https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=800&q=80',
        ],
        isAvailableNow: true,
        isFavorite: false,
        amenities: ['Parking', 'Washroom', 'Water', 'Locker', 'Floodlights'],
        description: 'Premium football turf with top-quality artificial grass. Perfect for 5v5 and 7v7 matches. Book your slot and enjoy the game with your squad.',
        about: 'Green Field Arena is Bangalore\'s premier football turf, featuring high-quality FIFA-approved artificial turf. With floodlights for evening games and excellent amenities, it\'s the number one choice for football enthusiasts.',
        openTime: '6:00 AM',
        closeTime: '11:00 PM',
        address: '12th Main Rd, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008',
        lat: 12.9784,
        lng: 77.6408,
        category: 'Football',
    },
    {
        id: '2',
        name: 'Smash Zone Cricket',
        location: 'Koramangala, Bangalore',
        distance: '2.5 km',
        rating: 4.6,
        reviewCount: 89,
        price: 1200,
        priceUnit: 'hour',
        sport: 'Cricket',
        image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
            'https://images.unsplash.com/photo-1540747913346-19212a4b423c?w=800&q=80',
        ],
        isAvailableNow: true,
        isFavorite: true,
        amenities: ['Parking', 'Washroom', 'Water', 'Locker'],
        description: 'Professional cricket ground with well-maintained pitch. Perfect for practice sessions and friendly matches.',
        about: 'Smash Zone offers an exceptional cricket experience with two professional pitches, practice nets, and advanced coaching facilities.',
        openTime: '5:00 AM',
        closeTime: '10:00 PM',
        address: '80 Feet Road, 4th Block, Koramangala, Bengaluru, Karnataka 560034',
        lat: 12.9352,
        lng: 77.6245,
        category: 'Cricket',
    },
    {
        id: '3',
        name: 'Ace Tennis Club',
        location: 'HSR Layout, Bangalore',
        distance: '3.1 km',
        rating: 4.9,
        reviewCount: 56,
        price: 600,
        priceUnit: 'hour',
        sport: 'Tennis',
        image: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
        ],
        isAvailableNow: false,
        isFavorite: false,
        amenities: ['Parking', 'Washroom', 'Water'],
        description: 'Top-tier tennis courts with professional coaching available.',
        about: 'Ace Tennis Club features 4 professional hard courts and 2 clay courts, offering the finest tennis experience in Bangalore.',
        openTime: '6:00 AM',
        closeTime: '9:00 PM',
        address: 'Outer Ring Rd, Sector 1, HSR Layout, Bengaluru, Karnataka 560102',
        lat: 12.9121,
        lng: 77.6446,
        category: 'Tennis',
    },
    {
        id: '4',
        name: 'Rally Point Badminton',
        location: 'Whitefield, Bangalore',
        distance: '4.8 km',
        rating: 4.7,
        reviewCount: 203,
        price: 400,
        priceUnit: 'hour',
        sport: 'Badminton',
        image: 'https://images.unsplash.com/photo-1664575601786-b00156752b61?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1664575601786-b00156752b61?w=800&q=80',
        ],
        isAvailableNow: true,
        isFavorite: true,
        amenities: ['Parking', 'Washroom', 'Water', 'Locker', 'Floodlights'],
        description: 'Best badminton facility in the city with 8 professional courts.',
        about: 'Rally Point has 8 indoor courts with wooden flooring, ensuring world-class playing conditions for beginners and professionals alike.',
        openTime: '6:00 AM',
        closeTime: '11:00 PM',
        address: 'ITPL Main Rd, Siddapura, Whitefield, Bengaluru, Karnataka 560048',
        lat: 12.9698,
        lng: 77.7499,
        category: 'Badminton',
    },
    {
        id: '5',
        name: 'SwimFit Aqua Center',
        location: 'Jayanagar, Bangalore',
        distance: '2.0 km',
        rating: 4.5,
        reviewCount: 78,
        price: 350,
        priceUnit: 'hour',
        sport: 'Swimming',
        image: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80',
        ],
        isAvailableNow: false,
        isFavorite: false,
        amenities: ['Parking', 'Washroom', 'Locker'],
        description: 'Olympic-size swimming pool for all levels of swimmers.',
        about: 'SwimFit Aqua Center features a 50m Olympic pool, a training pool, and professional coaching services.',
        openTime: '5:30 AM',
        closeTime: '9:00 PM',
        address: '40th Cross, 8th Block, Jayanagar, Bengaluru, Karnataka 560082',
        lat: 12.9254,
        lng: 77.5832,
        category: 'Swimming',
    },
    {
        id: '6',
        name: 'ProHoop Basketball',
        location: 'JP Nagar, Bangalore',
        distance: '3.5 km',
        rating: 4.4,
        reviewCount: 45,
        price: 700,
        priceUnit: 'hour',
        sport: 'Basketball',
        image: 'https://images.unsplash.com/photo-1546519638405-a2b5e4f3a2b1?w=800&q=80',
        images: [
            'https://images.unsplash.com/photo-1546519638405-a2b5e4f3a2b1?w=800&q=80',
        ],
        isAvailableNow: true,
        isFavorite: false,
        amenities: ['Parking', 'Washroom', 'Water', 'Floodlights'],
        description: 'Full-size basketball court with wooden flooring and proper lighting.',
        about: 'ProHoop offers NBA-regulation courts with professional flooring, perfect for competitive play and training sessions.',
        openTime: '6:00 AM',
        closeTime: '10:00 PM',
        address: '15th Cross, Phase 2, JP Nagar, Bengaluru, Karnataka 560078',
        lat: 12.9083,
        lng: 77.5853,
        category: 'Basketball',
    },
];

export const MOCK_TIME_SLOTS = {
    morning: [
        { id: 'm1', time: '06:00 AM', available: true, selected: false },
        { id: 'm2', time: '07:00 AM', available: false, selected: false },
        { id: 'm3', time: '08:00 AM', available: true, selected: false },
        { id: 'm4', time: '09:00 AM', available: true, selected: false },
        { id: 'm5', time: '10:00 AM', available: false, selected: false },
        { id: 'm6', time: '11:00 AM', available: true, selected: false },
    ],
    afternoon: [
        { id: 'a1', time: '12:00 PM', available: true, selected: false },
        { id: 'a2', time: '01:00 PM', available: true, selected: false },
        { id: 'a3', time: '02:00 PM', available: false, selected: false },
        { id: 'a4', time: '03:00 PM', available: true, selected: false },
        { id: 'a5', time: '04:00 PM', available: true, selected: false },
        { id: 'a6', time: '05:00 PM', available: false, selected: false },
    ],
    evening: [
        { id: 'e1', time: '06:00 PM', available: true, selected: false },
        { id: 'e2', time: '07:00 PM', available: false, selected: false },
        { id: 'e3', time: '08:00 PM', available: true, selected: false },
        { id: 'e4', time: '09:00 PM', available: true, selected: false },
        { id: 'e5', time: '10:00 PM', available: false, selected: false },
    ],
};

export const MOCK_BOOKINGS = [
    {
        id: 'BK001',
        turfId: '1',
        turfName: 'Green Field Arena',
        turfImage: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
        location: 'Indiranagar, Bangalore',
        date: 'Mon, 15 Mar 2026',
        time: '06:00 PM - 07:00 PM',
        duration: '1 Hour',
        sport: 'Football',
        status: 'upcoming',
        totalAmount: 800,
        bookingDate: '2026-03-15',
    },
    {
        id: 'BK002',
        turfId: '4',
        turfName: 'Rally Point Badminton',
        turfImage: 'https://images.unsplash.com/photo-1664575601786-b00156752b61?w=800&q=80',
        location: 'Whitefield, Bangalore',
        date: 'Wed, 18 Mar 2026',
        time: '08:00 AM - 09:00 AM',
        duration: '1 Hour',
        sport: 'Badminton',
        status: 'upcoming',
        totalAmount: 400,
        bookingDate: '2026-03-18',
    },
    {
        id: 'BK003',
        turfId: '2',
        turfName: 'Smash Zone Cricket',
        turfImage: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
        location: 'Koramangala, Bangalore',
        date: 'Fri, 7 Mar 2026',
        time: '09:00 AM - 10:00 AM',
        duration: '1 Hour',
        sport: 'Cricket',
        status: 'completed',
        totalAmount: 1200,
        bookingDate: '2026-03-07',
    },
    {
        id: 'BK004',
        turfId: '3',
        turfName: 'Ace Tennis Club',
        turfImage: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
        location: 'HSR Layout, Bangalore',
        date: 'Tue, 1 Mar 2026',
        time: '07:00 PM - 08:00 PM',
        duration: '1 Hour',
        sport: 'Tennis',
        status: 'completed',
        totalAmount: 600,
        bookingDate: '2026-03-01',
    },
    {
        id: 'BK005',
        turfId: '1',
        turfName: 'Green Field Arena',
        turfImage: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80',
        location: 'Indiranagar, Bangalore',
        date: 'Sat, 22 Feb 2026',
        time: '04:00 PM - 05:00 PM',
        duration: '1 Hour',
        sport: 'Football',
        status: 'cancelled',
        totalAmount: 800,
        bookingDate: '2026-02-22',
    },
];

export const MOCK_USER = {
    id: 'user1',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@gmail.com',
    phone: '+91 98765 43210',
    avatar: 'https://i.pravatar.cc/150?img=11',
    location: 'Indiranagar, Bangalore',
    joinedDate: 'March 2025',
};

export const SPORT_CATEGORIES = [
    { id: 'all', label: 'All', icon: '⚽' },
    { id: 'football', label: 'Football', icon: '⚽' },
    { id: 'cricket', label: 'Cricket', icon: '🏏' },
    { id: 'tennis', label: 'Tennis', icon: '🎾' },
    { id: 'badminton', label: 'Badminton', icon: '🏸' },
    { id: 'basketball', label: 'Basketball', icon: '🏀' },
    { id: 'swimming', label: 'Swimming', icon: '🏊' },
];
